### ISSUE TITLE
Module `https` does not exist in the Haste module map

### ISSUE THREAD

**Issue by chinhai077** [ajay2507/ebay-node-api#8]
I'm using this package in a react native project. With importing I'm using ES6 syntax

**Comment by ajay2507** [comment]
Hey @chinhai077,  I think this issue is with React Native
https://stackoverflow.com/questions/49835125/module-expo-does-not-exist-in-the-haste-module-map
Can you try upgrading the react native?. once do clean and install it again.
I can see the open issue in React Native
https://github.com/facebook/react-native/issues/19019

If you are still facing the issue, can you send me your repo link so that I can look into it.

**Comment by ajay2507** [comment]
@chinhai077  closing this, hoping that this issue is resolved.
